### ISSUE TITLE
Route /w passthrough changes server certificate passed to client

### ISSUE THREAD

**Issue by gaohoward** [code-ready/crc#1788]
### General information

  * OS: Linux (Fedora 31 x86_64)
  * Hypervisor: libvirtd
  * Did you run `crc setup` before starting it ? yes

## CRC version
```bash
CodeReady Containers version: 1.20.0+ef3f80d
OpenShift version: 4.6.6 (embedded in executable)

```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.6.6)
Disk Usage:      14.46GB of 32.72GB (Inside the CRC VM)
Cache Usage:     38.7GB
Cache Directory: /home/howard/.crc/cache
```

## CRC config
```bash
- http-proxy                            : http://squid.corp.redhat.com:3128
- https-proxy                           : http://squid.corp.redhat.com:3128
- memory                                : 10240
- no-proxy                              : .testing,localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.42.0/24,172.17.0.0/24
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### Steps to reproduce

  1. Create a pod that listens on port 61617 with ssl enabled. (in my case one of 2 amq-broker pods deployed via amq broker operator). service for this port is exposed and a route with passthrough is exposed for it.
  2. Create a java client to connect to the pod using the route.
  3. Run the client and watch the result

### Expected
The client should be able to connect and send/receive messages.

### Actual
The client can't establish the connection. Instead it gets the following error:
```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: 
....
```

### Logs
https://gist.github.com/gaohoward/ccfdda10c24069de2ccebdf60f5d7133

Some observations that I think it may related to this issue:
1. In the logs I can see the server certificate passed in to client is like:
```
"certificate" : {
    "version"            : "v3",
    "serial number"      : "01",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=ingress-operator@1606998023",
    "not before"         : "2020-12-03 12:20:23.000 UTC",
    "not  after"         : "2022-12-03 12:20:24.000 UTC",
    "subject"            : "CN=ingress-operator@1606998023",
    "subject public key" : "RSA",
    "extensions"         : [
      {
        ObjectId: 2.5.29.19 Criticality=true
        BasicConstraints:[
          CA:true
          PathLen:0
        ]
      },
      {
        ObjectId: 2.5.29.15 Criticality=true
        KeyUsage [
          DigitalSignature
          Key_Encipherment
          Key_CertSign
        ]
      },
      {
        ObjectId: 2.5.29.14 Criticality=false
        SubjectKeyIdentifier [
        KeyIdentifier [
        0000: E1 5F EA D7 0D DA 52 6F   D8 39 02 5C 4F AB A9 25  ._....Ro.9.\O..%
        0010: 31 20 7E 77                                        1 .w
        ]
        ]
      }
    ]}
]
)
```
However the client would expect the certificate to be like:
```
  "certificate" : {
    "version"            : "v3",
    "serial number"      : "6A E0 76 00",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "not before"         : "2020-12-16 03:00:32.000 UTC",
    "not  after"         : "2030-12-14 03:00:32.000 UTC",
    "subject"            : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "subject public key" : "RSA",
    "extensions"         : [
      {
        ObjectId: 2.5.29.14 Criticality=false
        SubjectKeyIdentifier [
        KeyIdentifier [
        0000: 29 08 A8 D4 11 B9 59 14   9D CC D4 91 79 2D 54 10  ).....Y.....y-T.
        0010: 67 D7 5E 54                                        g.^T
        ]
        ]
      }
    ]}
```
2. If I use directly the service ClusterIP to connect to the pod service, the client works as expected. i.e. it can find the trusted
cert and send/receive message successfully.

**Comment by cfergeau** [comment]
can you share the route/service yaml definitions that you use? By any chance, did you test these steps against a production openshift cluster, and  did it behave differently? I'm asking to try to understand if this is a crc-specific behaviour, or if this is a more general OpenShift issue.

**Comment by gaohoward** [comment]
@cfergeau Thanks for fast response. Maybe it's helpful that I provide a bit background:
I'm having this issue while investigating a more complex test scenario where  the broker pod was accessed by a MDB in a eap pod.
So I simplified the case a bit and hopefully I can get some clue.
I didn't test it on production openshift cluster.
I'll share the yamls following this.

**Comment by gaohoward** [comment]
`[howard@localhost 4362]$ oc get route ex-aao-all-0-svc-rte -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2020-12-17T08:57:58Z"
  labels:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
    statefulset.kubernetes.io/pod-name: ex-aao-ss-0
  managedFields:
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:ActiveMQArtemis: {}
          f:application: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9c509aee-5e4e-4aba-aeec-a20bd11147a7"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:port:
          .: {}
          f:targetPort: {}
        f:tls:
          .: {}
          f:insecureEdgeTerminationPolicy: {}
          f:termination: {}
        f:to:
          f:kind: {}
          f:name: {}
          f:weight: {}
        f:wildcardPolicy: {}
    manager: activemq-artemis-operator
    operation: Update
    time: "2020-12-17T08:57:58Z"
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:ingress: {}
    manager: openshift-router
    operation: Update
    time: "2020-12-17T08:57:58Z"
  name: ex-aao-all-0-svc-rte
  namespace: default
  ownerReferences:
  - apiVersion: broker.amq.io/v2alpha4
    blockOwnerDeletion: true
    controller: true
    kind: ActiveMQArtemis
    name: ex-aao
    uid: 9c509aee-5e4e-4aba-aeec-a20bd11147a7
  resourceVersion: "45307"
  selfLink: /apis/route.openshift.io/v1/namespaces/default/routes/ex-aao-all-0-svc-rte
  uid: 558c5b0d-6c1f-42f0-b518-6951ae88e589
spec:
  host: ex-aao-all-0-svc-rte-default.apps-crc.testing
  port:
    targetPort: all-0
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: ex-aao-all-0-svc
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2020-12-17T08:57:58Z"
      status: "True"
      type: Admitted
    host: ex-aao-all-0-svc-rte-default.apps-crc.testing
    routerCanonicalHostname: apps-crc.testing
    routerName: default
    wildcardPolicy: None
`

**Comment by gaohoward** [comment]
`[howard@localhost 4362]$ oc get service ex-aao-all-0-svc -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-17T08:57:57Z"
  labels:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:ActiveMQArtemis: {}
          f:application: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9c509aee-5e4e-4aba-aeec-a20bd11147a7"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":61617,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:publishNotReadyAddresses: {}
        f:selector:
          .: {}
          f:ActiveMQArtemis: {}
          f:application: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: activemq-artemis-operator
    operation: Update
    time: "2020-12-17T08:57:57Z"
  name: ex-aao-all-0-svc
  namespace: default
  ownerReferences:
  - apiVersion: broker.amq.io/v2alpha4
    blockOwnerDeletion: true
    controller: true
    kind: ActiveMQArtemis
    name: ex-aao
    uid: 9c509aee-5e4e-4aba-aeec-a20bd11147a7
  resourceVersion: "45273"
  selfLink: /api/v1/namespaces/default/services/ex-aao-all-0-svc
  uid: dfca956c-f5d1-4e39-82b9-81120c82df63
spec:
  clusterIP: 172.25.3.106
  ports:
  - name: all-0
    port: 61617
    protocol: TCP
    targetPort: 61617
  publishNotReadyAddresses: true
  selector:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
    statefulset.kubernetes.io/pod-name: ex-aao-ss-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
`

**Comment by gaohoward** [comment]
And here is some relevant debug message when I directly use service's ClusterIP to connect, you can see the client found the trusted cert.
```
javax.net.ssl|FINE|0B|Thread-0 (ActiveMQ-client-netty-threads)|2020-12-17 13:03:46.052 UTC|Logger.java:765|Consuming server Certificate handshake message (
"Certificates": [
  "certificate" : {
    "version"            : "v3",
    "serial number"      : "6A E0 76 00",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "not before"         : "2020-12-16 03:00:32.000 UTC",
    "not  after"         : "2030-12-14 03:00:32.000 UTC",
    "subject"            : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "subject public key" : "RSA",
    "extensions"         : [
      {
        ObjectId: 2.5.29.14 Criticality=false
        SubjectKeyIdentifier [
        KeyIdentifier [
        0000: 29 08 A8 D4 11 B9 59 14   9D CC D4 91 79 2D 54 10  ).....Y.....y-T.
        0010: 67 D7 5E 54                                        g.^T
        ]
        ]
      }
    ]}
]
)
javax.net.ssl|FINE|0B|Thread-0 (ActiveMQ-client-netty-threads)|2020-12-17 13:03:46.057 UTC|Logger.java:765|Found trusted certificate (
  "certificate" : {
    "version"            : "v3",
    "serial number"      : "6A E0 76 00",
    "signature algorithm": "SHA256withRSA",
    "issuer"             : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "not before"         : "2020-12-16 03:00:32.000 UTC",
    "not  after"         : "2030-12-14 03:00:32.000 UTC",
    "subject"            : "CN=Tom Ross, OU=GSS, O=Red Hat, L=Reading, ST=Berks, C=UK",
    "subject public key" : "RSA",
    "extensions"         : [
      {
        ObjectId: 2.5.29.14 Criticality=false
        SubjectKeyIdentifier [
        KeyIdentifier [
        0000: 29 08 A8 D4 11 B9 59 14   9D CC D4 91 79 2D 54 10  ).....Y.....y-T.
        0010: 67 D7 5E 54                                        g.^T
        ]
        ]
      }
    ]}
)
```

**Comment by gaohoward** [comment]
My test client doesn't connect if using this connection url:

tcp://ex-aao-all-0-svc-rte-default.apps-crc.testing:443?sslEnabled=true&trustStorePath=client.ts&trustStorePassword=secret&sniHost=localhost

and works with this url:

tcp://172.25.3.106:61617?sslEnabled=true&trustStorePath=/etc/amq-broker-ssl-secret-volume/client.ts&trustStorePassword=secret&sniHost=localhost

172.25.3.106 is the service's ClusterIP

Not sure if that can give some more relevant details, but anyway.

**Comment by cfergeau** [comment]
`sniHost=localhost`? I'd expect `ex-aao-all-0-svc-rte-default.apps-crc.testing` in order to match `spec.host` in the route yaml?

**Comment by cfergeau** [comment]
Might be worth looking at the certs returned by `openssl s_client ex-aao-all-0-svc-rte-default.apps-crc.testing:443 |openssl x509 -text` and compare with what your client application is getting

**Comment by gaohoward** [comment]
That 'localhost' is to match the sniHost on the server pod (broker) side. Here is the server port settings:

<acceptor name="all">tcp://ex-aao-ss-0.ex-aao-hdls-svc.default.svc.cluster.local:61617?protocols=AMQP,CORE,HORNETQ,MQTT,OPENWIRE,STOMP;sslEnabled=true;keyStorePath=/etc/amq-broker-ssl-secret-volume/broker.ks;keyStorePassword=secret;trustStorePath=/etc/amq-broker-ssl-secret-volume/client.ts;trustStorePassword=secret;;sslProvider=JDK;**sniHost=localhost**;anycastPrefix=jms.queue.;multicastPrefix=jms.topic.;connectionsAllowed=10;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>

**Comment by gaohoward** [comment]
Not sure what that means but I get this output:
```
[howard@localhost ssl-test-client]$ openssl s_client ex-aao-all-0-svc-rte-default.apps-crc.testing:443 |openssl x509 -text
139646888531776:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:ssl/record/rec_layer_s3.c:1543:SSL alert number 112
unable to load certificate
140097557231424:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```

**Comment by cfergeau** [comment]
> That 'localhost' is to match the sniHost on the server pod (broker) side. Here is the server port settings:

What I'm worried is that when you connect to `ex-aao-all-0-svc-rte-default.apps-crc.testing:443`, the route selection (and thus the certificate to return) uses SNI. If you indicate `localhost`, then the cluster would return the wrong certs.

**Comment by gaohoward** [comment]
Tried remote 'sniHost' from both server and client side. Now the client can connect successfully.

**Comment by gaohoward** [comment]
Is that by design that route treat localhost sniHost this way?

**Comment by cfergeau** [comment]
It's not really `localhost` which is special here. If you set `sniHost` to anything but `ex-aao-all-0-svc-rte-default.apps-crc.testing`, you wont get the certificates that you specified for the `ex-aao-all-0-svc-rte-default.apps-crc.testing` route.
As far as I understand, this is the purpose of SNI, ie TLS certificate selection when one daemon listening on a single port must provide different certs for different domains.

**Comment by gaohoward** [comment]
I see. Thanks @cfergeau.

**Comment by gaohoward** [comment]
Hi @cfergeau

I did some more test scenarios:

1. Changed sniHost to **somehost** instead of **localhost** on both client and server pod. The router seems still
return its own cert to client. The client url is like:

`tcp://ex-aao-all-0-svc-rte-default.apps-crc.testing:443?sslEnabled=true&**sniHost=somehost**&trustStorePath=client.ts&trustStorePassword=secret`

Resulting in same exception:
`sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
2. Then **remove** sniHost from client, url like this:

`tcp://ex-aao-all-0-svc-rte-default.apps-crc.testing:443?sslEnabled=true&trustStorePath=client.ts&trustStorePassword=secret`

and got a different exception:

**javax.net.ssl.SSLException: Received fatal alert: unrecognized_name**

This actually was from server pod because on server log I see this:

`SSL handshake failed for client from /10.116.0.1:35820: javax.net.ssl.SSLHandshakeException: Unrecognized server name indication.`

It looks like if client doesn't supply a sniHost, the route will pass its own host name to the server.

**Comment by tommaso-borgato** [comment]
We had the same problem when trying to connect though the AMQ OpenShift Route from some EAP POD to the AMQ Broker POD;

We deployed the AMQ Broker using the AMQ Operator with the following CR:

`apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: amq-broker
  namespace: somenamespace
spec:
  acceptors:
    - port: 61617
      verifyHost: false
      expose: true
      multicastPrefix: jms.topic.
      name: all
      connectionsAllowed: 10
      sslEnabled: true
      sniHost: localhost
      protocols: all
      sslSecret: amq-broker-ssl-secret
      sslProvider: JDK
      anycastPrefix: jms.queue.
  connectors:
    - port: 22222
      verifyHost: true
      wantClientAuth: true
      expose: true
      enabledCipherSuites: 'SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA'
      host: localhost
      needClientAuth: true
      name: connector0
      sslEnabled: false
      sniHost: localhost
      enabledProtocols: 'TLSv1,TLSv1.1,TLSv1.2'
      sslProvider: JDK
  console:
    expose: true
  deploymentPlan:
    image: 'registry.redhat.io/amq7/amq-broker:7.6'
    journalType: nio
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
  upgrades:
    enabled: false
    minor: false
`

Removing the `sniHost: localhost` solved the issue

**Comment by gaohoward** [comment]
Hi,
Can someone help with this? The issue is still seeing by more users.
Thanks

**Comment by praveenkumar** [comment]
@gaohoward will look into this.

**Comment by gbraad** [comment]
> The issue is still seeing by more users.

So far we have only seen people dealing with 'Artemis' to report this... you and Tommasso. Can you explain in short what the issue is and it prevents for you.

**Comment by cfergeau** [comment]
[Artemis documentation](https://activemq.apache.org/components/artemis/documentation/latest/configuring-transports.html) contains this about `sniHost`:

> When used on an acceptor the sniHost is a regular expression used to match the server_name extension on incoming SSL connections. If the name doesn't match then the connection to the acceptor will be rejected. A WARN message will be logged if this happens. If the incoming connection doesn't include the server_name extension then the connection will be accepted.

> When used on a connector the sniHost value is used for the server_name extension on the SSL connection.

My feeling is that in the `ActiveMQArtemis` CDR, `sniHost` should not be `localhost`, but unspecified as noted by Tommaso, or set to match the route it is exposed as?

**Comment by gaohoward** [comment]
@praveenkumar Unfortunately I haven't tested on production environment. I'm working on artemiscloud project which is an operator for amq-brokers on k8s and openshift. One of our EAP users has a test case where this issue occurs. 
Tommasso may have seen it in his production environment. So I'm pretty convinced that there is a real issue about route.
To summerize the issue in a few points according to my observation:
1. A broker pod has a SSL/TLS port listening and exposed as a service. The broker is setup with a sniHost=localhost and a certificate associated with "localhost"
2. a route with passthrough policy is deployed to route traffic to the above service
3. an external client tries to connect the service through the route
4. if client connects with "sniHost=localhost" specified, the route seems to pass the information to broker and broker returns the 'localhost' certificate back. however the route seems to drop the certificate and instead pass its own certificate to client, which client doesn't trust, therefore connection failed.
5. if client connects with no sniHost at all, the route seems to pass its own host name (e.g. ex-aao-all-0-svc-rte-default.apps-crc.testing) as sniHost to broker, which broker doesn't have any record in its sniHost list, therefore broker throws error like: **SSL handshake failed for client from /10.116.0.1:35820: javax.net.ssl.SSLHandshakeException: Unrecognized server name indication.** and the connection failed.

So I'm not sure this is what a 'passthrough' route should behave. I mean why route interferes with client-server SSL handshake by changing the sniHost setting from client and server/broker? Or is it a matter of router administration/configuration so a 'passthough' route can behave differently?

**Comment by cfergeau** [comment]
> The broker is setup with a sniHost=localhost and a certificate associated with "localhost"

But is this correct? If you are connecting to your broker from an external hostname, and are connecting to it with TLS passthrough, you'll need a certificate associated with this external hostname? 

> if client connects with no sniHost at all, the route seems to pass its own host name [...]
> I mean why route interferes with client-server SSL handshake by changing the sniHost setting from client and server/broker?

I think this is how SNI works, and it's probably the client which sets SNI to the hostname you connect to when it's not specified. See https://aws.amazon.com/blogs/networking-and-content-delivery/unpacking-sni-based-ssl-and-dedicated-ip-ssl-for-amazon-cloudfront/
https://www.me2digital.com/blog/2019/05/haproxy-sni-routing/ says that this is how OpenShift routing works, through SNI.
The only way to use your route and its certificates is probably to have the right host in SNI, not localhost.
