### ISSUE TITLE
[BUG] Inconsistent cleanup logs from built artifacts for MacOS

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2195]
### General information

Tested on QE Environment

## CRC version

Pre released 1.25.0
  

## Host Operating System

MacOS

### Steps to reproduce

  1. clone crc master branch
  2. make 
  3. crc cleanup
  4. make NO_CODESIGN=1 BUNDLE_DIR=./../ out/macos-amd64/crc-macos-amd64.pkg
  5. install crc from generated pkg
  6. crc cleanup

### Expected

crc cleanup command output should be the same

### Actual

Probably related to #2177, now binary does not install the tray so on cleanup messages referring to it are lost. So the output is different depending on the crc used (pkg vs binary)

### Logs

crc cleanup (from make):
```bash
redhat@blr-crc-macserver kk % ~/go/bin/crc version                                                                           
CodeReady Containers version: 1.24.0+c2886ff
OpenShift version: 4.7.5 (not embedded in executable)
redhat@blr-crc-macserver kk % ~/go/bin/crc cleanup                                                                           
INFO Removing /etc/resolver/testing file          
INFO Unload CodeReady Containers daemon           
INFO Stopping CRC Hyperkit process                
INFO Removing pull secret from the keyring        
INFO Removing older logs                          
INFO Removing CRC Machine Instance directory      
INFO Removing hosts file records added by CRC     
Cleanup finished
```

crc cleanup (from pkg build)
```bash
redhat@blr-crc-macserver kk % crc version
CodeReady Containers version: 1.24.0+c2886ff
OpenShift version: 4.7.5 (not embedded in executable)
redhat@blr-crc-macserver kk % crc cleanup
INFO Unload CodeReady Containers tray             
INFO Removing launchd configuration for tray      
INFO Removing /etc/resolver/testing file          
INFO Unload CodeReady Containers daemon           
INFO Stopping CRC Hyperkit process                
INFO Removing pull secret from the keyring        
INFO Removing older logs                          
INFO Removing CRC Machine Instance directory      
INFO Removing hosts file records added by CRC     
Cleanup finished
```

**Comment by cfergeau** [comment]
Is this fixed by #2196, or is #2196 just an improvement but not a full fix? I would assume the former, and so this issue can be closed?

**Comment by praveenkumar** [comment]
fixed by #2196

**Comment by adrianriobo** [comment]
I think this is not fully fixed, as this is still happening, the fix catch the minimum common behavior. 

As the test is run on both distribution mechanisms (binary and pkg)..and I do not think the type of distribution should condition the test, that fix allows to check the common behavior for both.

Other question is the long term solution will be focus on pkg, and for that more robust checks are expected on e2e testing. So just as reminder of the issue I would prefer to keep this open as long as we keep distributing the binary.
