### ISSUE TITLE
[BUG] Windows : CRC negatively impacts DNS resolution when not running.

### ISSUE THREAD

**Issue by BarDweller** [code-ready/crc#926]
### General information

  * OS:  Windows
  * Hypervisor:Hyper-V
  * Did you run `crc setup` before starting it YES

## CRC version
```bash
crc version: 1.3.0+918756b
OpenShift version: 4.2.10 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     24.92GB
Cache Directory: C:\Users\Ozzy\.crc\cache
```

## CRC config
```bash
- cpus                                  : 6
- memory                                : 32768
```

## Host Operating System
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
```

### Steps to reproduce

  1. Install crc.. do the whole crc setup, crc start, use crc for a bit, then do crc stop.
  2. Try using a web browser, or building with maven, notice all dns resolutions are now taking multiple seconds to resolve instead of being instant.
  3. do crc start (in my case .. crc start -n 8.8.8.8)
  4. Try using a web browser, or building with maven, notice all dns resolutions are now working as expected again.. 

### Expected

When CRC isn't running, it shouldn't be screwing up the platforms dns resolution. 

### Actual

CRC's adding of a DNS Server to the default virtual switch means every DNS lookup tries to go to the CRC ip (192.168.75.246 in my case) .. which is only available when CRC is running. This lookup adds noticeable seconds to DNS resolutions, and seems to cause issues with Maven/Docker builds that expect DNS lookups to occur in a timely manner. 

Removing the DNS entry via the network connections panel with start/run/ncpa.cpl and right clicking vEthernet (Default Switch), double click Internet Protocol Version TCP/IP v4, and removing the ip address from the 'Use the following DNS server addresses' box, restored normal DNS behavior to my system.

**Comment by gbraad** [comment]
We are aware of this. Still looking into a solution that might not need the local DNS resolution configured on the interface.

**Comment by BarDweller** [comment]
Any chance of an update in the docs somewhere to help mitigate the impact of this until it's resolved? It took me quite a while to figure out what CRC had done, so I could undo it. 

The impact is quite nasty, as it affects the developers machine even if they remove CRC.

**Comment by BarDweller** [comment]
A possible solution might be to run dnsmasq in it's own tiny vm, independent of crc, allowing that vm to remain operational even while crc is stopped ?

**Comment by gbraad** [comment]
running an additional VM would use resources we prefer not to waste. We considered this for Minishift and decided not to after tests. The alternative would have been to run CoreDNS, but this has proven to be unstable.

A reboot should have resolved the issue, right?

**Comment by gbraad** [comment]
Does `Restart-NetAdapter` [0] reset these values?

[0] := https://docs.microsoft.com/en-us/powershell/module/netadapter/restart-netadapter

**Comment by aguther** [comment]
I think it‘s not the right way to change the configuration of the default switch (where all Hyper-V machines are using by default). The VM is also very resource hungry and people will not have it running all the time.

What about adding a special vSwitch only for the usage of CRC?

**Comment by BarDweller** [comment]
@gbraad Didn't try a reboot.. once I'd figured out what CRC did to the default switch, I just undid it by hand via the UI. I'll just need to remember to reverse that whenever I actually need to run CRC (or automate it via some wrapper scripts.. but it's enough of a disincentive to use CRC that maybe I'll just go back to kube in docker for now). 

@aguther I think the CRC installer already supports using it's own switch, but you have to create one called 'crc' before you do the install, at least I saw the code doing something like that, even if there doesn't appear to be docs saying why you'd want to do it, or how.

**Comment by gbraad** [comment]
Using a crc named switch is part of a test for windows 10 enterprise. He haven't finalized the setup code and docs. But yes, this works as an alternative.

**Comment by jeffmaury** [comment]
Facing the issue and after crc is stopped, minishift/cdk is unable to start.

**Comment by gbraad** [comment]
@jeffmaury @jeffsaremi Can you try `Set-DNSClientServerAddress "vEthernet (Default Switch)" -ResetServerAddresses` after stopping the VM ?

**Comment by jeffsaremi** [comment]
@gbraad 
Yes the mentioned command fixed my problem. I just had to run it in an admin shell

**Comment by gbraad** [comment]
Fixed with #1155

**Comment by bavibm** [comment]
Hello, I'm still experiencing this issue with the latest CRC version.

crc version
```
CodeReady Containers version: 1.12.0+6710aff
OpenShift version: 4.4.8 (embedded in binary)
```

crc status

```
CRC VM:          Running
OpenShift:       Running (v4.4.8)
Disk Usage:      12.89GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.81GB
Cache Directory: XXX
```
crc config
```
- cpus                                  : 4
- memory                                : 16384
- pull-secret-file                      : XXX
```
os
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041
```

**Comment by nddipiazza** [comment]
hey @gbraad i'm trying to sort through this issue - i ran `Set-DNSClientServerAddress "vEthernet (Default Switch)" -ResetServerAddresses` but after I did this, now I cannot use crc anymore. It fails to find the dns entries. 

Is there a "turn dns back on for openshift" powershell command I can run? 

That way I can turn on the dns changes when i want to use crc, and turn them off again when I no longer want them? thanks.

**Comment by guillaumerose** [comment]
@nddipiazza Latest crc introduce a new network mode that should fix your issue. Can you try https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack ? Thanks.

**Comment by nddipiazza** [comment]
Sure! On it now. @guillaumerose

**Comment by nddipiazza** [comment]
OK ran the instructions. I have openshift up and running and dns appears to be resolving quickly.
